source 'https://rubygems.org'

gem "jekyll", "~> 4.4.1" # installed by `gem jekyll`
gem "jekyll-sass-converter", ">= 3.1.0" # silence_deprecations for theme Sass
gem "logger" # silence Ruby 4.0 default-gem warning on Ruby 3.4+
gem "webrick", "~> 1.8" # required for `jekyll serve` on Ruby 3+

gem "just-the-docs", "0.10.1" # pinned to the current release
# gem "just-the-docs"        # always download the latest release

gem "jekyll-redirect-from"